// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW8AmV7WN2gDhZNg8lEYE-dJ55UAblyq4',
    appId: '1:1019205678908:ios:cef67a76eaec9414941039',
    messagingSenderId: '1019205678908',
    projectId: 'azuaytkd',
    storageBucket: 'azuaytkd.firebasestorage.app',
    iosBundleId: 'com.code48.azuaytkd.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBjW1R-VB7aoJiXRnwJyMXD33i-HvChoQE",
    appId: "1:1019205678908:android:915b0f50fc474f6c941039",
    messagingSenderId: "1019205678908",
    projectId: "azuaytkd",
    storageBucket: "azuaytkd.firebasestorage.app",
  );

}